### ISSUE TITLE
Error 500 on fits

### ISSUE THREAD

**Issue by molbal** [molbal/abyss-tracker#63]
**Describe the bug**
kenlon#8274: I'm getting a 500 Server Error when trying to look at fits, any of them. Is something broken?

**Log**
```
[2020-08-28 00:08:21] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [itempricecalculator could not find for typeID 56092] is not defined. at /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:192)
[stacktrace]
#0 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve()
#1 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get()
#2 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(87): Illuminate\\Log\\LogManager->driver()
#3 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Log\\LogManager->channel()
#4 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/app/Http/Controllers/Loot/LootValueEstimator.php(199): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/app/Http/Controllers/Loot/LootValueEstimator.php(49): App\\Http\\Controllers\\Loot\\LootValueEstimator->process()
#6 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/app/Http/Controllers/Loot/LootValueEstimator.php(73): App\\Http\\Controllers\\Loot\\LootValueEstimator->__construct()
#7 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/app/Http/Controllers/AbyssController.php(224): App\\Http\\Controllers\\Loot\\LootValueEstimator::difference()
#8 [internal function]: App\\Http\\Controllers\\AbyssController->store()
#9 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#10 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#11 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#12 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#13 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#14 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#15 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#23 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#32 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#34 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/molbal/nova-mirror/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#37 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#45 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#47 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /var/www/vhosts/abyss.eve-nt.uk/httpdocs/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"} 
```

**Comment by molbal** [comment]
Fixed in 1.7
